name: ci

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cc: [clang, gcc]
    steps:
      - uses: actions/checkout@v5
      - name: build with ${{ matrix.cc }}
        run: |
          # Since ubuntu-latest does not ship with OpenSSL >= v3.5, dynamic linking will fail unless we build and install it.
          git clone -b openssl-3.6 https://github.com/openssl/openssl
          pushd openssl
          git fetch --tags
          git checkout openssl-3.6.0
          ./config --prefix=/opt/openssl36 shared
          make -j $(nproc --all)
          make install
          popd

          make sslscan LDFLAGS=-L/opt/openssl36 CFLAGS=-I/opt/openssl36/include
          make static
        env:
          CC: ${{ matrix.cc }}
  build_mingw:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: install mingw-w64
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq mingw-w64
      - name: build with mingw-w64
        run: |
          make -f Makefile.mingw
